spring:
  application:
   name: Ejemplo Spring Boot
  datasource:
   url: jdbc:mysql://localhost:3306/db_springdemo
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
idioma: Spanish
custom:
  autor: Esteban