spring.application.name=configserver
server.port=8888
#spring.cloud.config.server.git.uri=file:///C:/Cursos/Java//Cursos/2026-03-GobVasco/workspace/config-files
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/Cursos/Java//Cursos/2026-03-GobVasco/workspace/config-files
